name: release

on: 
    push:
         branches:
           - main

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 12
            - run: npm install
            - run: npm whoami
            - uses: JS-DevTools/npm-publish@v1
              with:
                token: ${{ secrets.NPM_TOKEN }}