name: release

on: 
    push:
         branches:
           - main

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.4.2

            - name: node
              uses: actions/setup-node@v3.2.0
              with:
                  node-version: 16
            - uses: JS-DevTools/npm-publish@v1
              with:
                token: ${{ secrets.NPM_AUTH_TOKEN2 }}
              run: npm whoami

             

       